---
- name: "Install additional packages"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - gpg
    - nginx
    - util-linux-extra

- name: Install pre-requisites via apt
  apt:
    name:
      - python3-openshift
      - python3-yaml
      - python3-kubernetes
    state: present