---
- name: "Download minikube"
  shell: "curl -L https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 -o minikube"

- name: "Make executable"
  shell: "chmod +x minikube"

- name: "Copy to path"
  shell: "sudo mv minikube /usr/local/bin/"

- name: "Get minikube version"
  shell: "minikube version"
  register: minikube_version

- name: "Check version"
  debug:
    msg: "{{ minikube_version }}"

- name: "Purge"
  shell: "minikube delete --all --purge"

- name: "Start minikube"
  shell: "minikube start --cpus=4 --memory=8192 --driver=docker --force --force-systemd=true"

- name: "Get minikube status"
  shell: "minikube status"
  register: minikube_status

- name: "Check minikube status"
  debug:
    msg: "{{ minikube_status }}"

- name: "minikube enable regestry"
  shell: "minikube addons enable registry"