---
- name: "Enable ingress"
  shell: "minikube addons enable ingress"
  become: yes

- name: "Create Moon namespace"
  shell: "sudo kubectl create namespace moon --dry-run=client -o yaml | kubectl apply -f -"
  register: namespace_result
  changed_when: "'created' in namespace_result.stdout"

- name: "Add helm repo"
  shell: "helm repo add aerokube https://charts.aerokube.com"
  register: repo_result
  changed_when: "'has been added' in repo_result.stdout"

- name: "Update helm repos"
  shell: "helm repo update"

- name: "Wait for ingress-nginx controller to be ready"
  ansible.builtin.shell: >
    kubectl wait --namespace ingress-nginx
    --for=condition=ready pod
    --selector=app.kubernetes.io/component=controller
    --timeout=300s
  changed_when: false

- name: "Deploy moon"
  shell: |
    helm upgrade --install moon aerokube/moon2 \
      --namespace moon \
      --create-namespace \
      --set ingress.host=moon.aerokube.local \
      --set ui.enabled=true \
      --wait

- name: "Get Minikube IP"
  ansible.builtin.shell: "minikube ip"
  register: minikube_ip
  changed_when: false

- name: "Set hosts"
  shell: "echo '{{ minikube_ip.stdout }} moon.aerokube.local' | sudo tee -a /etc/hosts"