---
- name: "Enable ingress"
  shell: "minikube addons enable ingress"

- name: "Create Moon namespace"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: Moon
    state: present

- name: "Add helm repo"
  kubernetes.core.helm_repository:
    name: aerokube
    repo_url: https://charts.aerokube.com

- name: Deploy moon
  kubernetes.core.helm:
    name: moon
    chart_ref: aerokube/moon2
    release_namespace: moon
    wait: true
    create_namespace: false
    values:
      ingress:
        host: moon.aerokube.local

- name: Deploy moon
  kubernetes.core.helm:
    name: moon
    chart_ref: aerokube/moon2
    release_namespace: moon
    wait: true
    create_namespace: false
    values:
      ui:
        enabled: true